### ISSUE TITLE
Probleme mit Abkürzungen auf Sub-Domain

### ISSUE THREAD

**Issue by webozz** [Sioweb/Glossar#10]
Hey,
ich schaue gerade ob ich die Extension in einem Projekt einsetzen kann. Sieht soweit sehr gut aus, macht alles was ich brauche! (sehr fein :) )

Allerdings habe ich das Problem, dass die Abkürzungen auf der Seite der Subdomain nicht auftauchen. Beim Aufbauen des Glossars in der Systemwartung scheinen diese nicht berücksichtigt zu werden.

Ist das Problem bekannt?

Viele Grüße
Oskar

**Comment by Sioweb** [comment]
Danke für die Info. Das Problem war mir bislang noch nicht bekannt, ich kann mir aber vorstellen woran es liegt. Evt komme ich diese Woche noch dazu den Bug zu lösen.

Danke & Lg
Sascha

**Comment by webozz** [comment]
Danke für die schnelle Antwort. Wir haben aber einen Weg gefunden...
Und zwar wenn man sich im Contao Backend mit der Subdomain anmeldet und die Indizierung startet, lassen sich die Abkürzungen auch auf den Seiten der Subdomain verwenden!

**Comment by Sioweb** [comment]
Ho! 

Hat lange gedauert aber die neueste Version hat das jetzt drin.

Lg
