### ISSUE TITLE
news4ward Reader wird nicht unterstützt

### ISSUE THREAD

**Issue by MacKP** [Sioweb/Glossar#11]
Hallo,
wenn ich das richtig verstehe, dann müsste jede Erweiterung (die wie News aufgebaut ist mit Liste und Leser) speziell von dir berücksichtigt werden vom Code?
Oder sollte das einfach so gehen?
Ich hab hier die news4ward Erweiterung und das funktioniert an sich. Nur leider nicht auf der Reader-Seite. (Wobei ich mir einbilde, das es kurz funktioniert hat und nach weiterem rumspielen dann doch nicht mehr..., aber ich bekomm es nicht wieder in einen Zustand wo es funktioniert, also kann es auch Einbildung gewesen sein _g_).

Viele Grüße

**Comment by Sioweb** [comment]
Vermutlich wird das Feature nun unterstützt durch den Fix neulich. Ich schließe mal bis sich das Gegenteil herausstellt o:
