### ISSUE TITLE
Kein "Glossar aufbauen"-Button in Contao 3.5.16

### ISSUE THREAD

**Issue by pyretta** [Sioweb/Glossar#12]
Hallo,
ich hoffe ich bin hier richtig. Habe die neueste Version SWGlossar 4.3.2 und ajax 1.1.6 installiert. Bei mir wird der Button "Glossar aufbauen" unter Systemwartung nicht angezeigt und die Glossar Begriffe werden auch nicht im Content hervorgehoben. Ich nutze Contao 3.5.16 mit einem Patch der Search.php der noch nicht veröffentlichten Version 3.5.17 (vom Contao Community Forum). 
Muss ich noch etwas installieren oder einstellen? 
Oder handelt es sich um eine Inkompatibilität zur neuesten Contao Version?

Vielen Dank im Voraus für jede Hilfe.

**Comment by Sioweb** [comment]
Ho!

Danke für die Meldung. Ja hier ist gut :)

Ich schaue mir dass an sobald ich Zeit hab, oder kannst du mir evt. einen FTP-Zugang einrichten? Dann kann ich es evt direkt bei dir Lösen und die neue Version hochladen.

Danke & Lg
Sascha

**Comment by pyretta** [comment]
Hi Sascha,
vielen Dank für die schnelle Antwort. FTP-Zugang kann ich dir einrichten. Brauchst du dann Rootrechte auf das Contao-Verzeichnis oder reicht es auf das Modul-Verzeichnis einzuschränken? Und wie gebe ich dir die Zugangsdaten?

**Comment by Sioweb** [comment]
Am Besten über support a t sioweb.de
