### ISSUE TITLE
Glossar findet nicht alle Abkürzungen

### ISSUE THREAD

**Issue by MacKP** [Sioweb/Glossar#14]
Ich bins mal wieder. Abkürzungen mit Punkten (und kurze wie .e.V.) funktionieren ja inzwischen ohne Probleme. Ich hab jetzt allerdings bei einer Installation ein paar Begriffe, die nicht als Abkürzung gefunden werden. Beispiel:

Im Text steht SLV-GE-NRW

GE und NRW werden gefunden. Leider das SLV nicht. 

Meine Einstellungen:
- Glossar aktivieren (An)
- Glossar in der Systemwartung/Daten bereinigen anzeigen (An)
- Begriffe als Headline aktivieren (Aus)
- Pluralsuche deaktivieren (Aus)
- Von der Suche ausgeschlossene Inhalte einbeziehen (An)
- Dann alles weitere aus
- Strikte Suche 'Alles finden'
- Pluralsuche enthält: ")(=?.,;~:'\>\&lt;+\/\&lt;

Und das war es. Ich habe auch schon einiges umgestellt. Leider hatte ich mit keiner Einstellung erfolg.

Wenn du noch mehr Infos brauchst, dann gib einfach Bescheid ;-)

Viele Grüße

**Comment by Sioweb** [comment]
Ho! Danke

Ich hab gerade nur beschränkt Zugang zum Netz wegen Umzug. Ich hab evt Mittwoch wieder Internet und versuche mich bis nächste Woche darum gekümmert zu haben - Erinnere mich bitte sonst noch mal.

**Comment by MacKP** [comment]
Super, danke schon mal!
Ich hab das ganze auch noch mal mit der Version von hier ausprobiert (per Hand installiert). Brachte leider auch keine Besserung. Allerdings muss ich dann aufpassen, das ich bestimmte Felder in der Tabelle nicht lösche (sonst funktioniert die Erweiterung natürlich nicht mehr):
'''
ALTER TABLE `tl_calendar` DROP `glossar_disallow`;

	

ALTER TABLE `tl_calendar_events` DROP `glossar`;

	

ALTER TABLE `tl_calendar_events` DROP `fallback_glossar`;

	

ALTER TABLE `tl_calendar_events` DROP `glossar_time`;

	

ALTER TABLE `tl_faq` DROP `glossar`;

	

ALTER TABLE `tl_faq` DROP `fallback_glossar`;

	

ALTER TABLE `tl_faq` DROP `glossar_time`;

	

ALTER TABLE `tl_faq_category` DROP `glossar_disallow`;

	

ALTER TABLE `tl_news` DROP `glossar`;

	

ALTER TABLE `tl_news` DROP `fallback_glossar`;

	

ALTER TABLE `tl_news` DROP `glossar_time`;

	

ALTER TABLE `tl_news_archive` DROP `glossar_disallow`;
'''

Eventuell gibt es da also noch ein anderes Problemchen ;-)

Viele Grüße

**Comment by MacKP** [comment]
Kleine Erinnerung ;-)
Noch als Ergänzung: auch so etwas wie 'GGG' wird nicht gefunden (steht einzeln im Text).

Viele Grüße

**Comment by Sioweb** [comment]
Danke :)

**Comment by Sioweb** [comment]
Ho!

Ich hab es eben bei mir getestet. Dazu habe ich SLV, GE und NRW als Abkürzung eingetragen und jeweils die Pluralsuche deaktiviert. 

http://playground.sioweb.de/home.html

Das funktioniert bei mir, allerdings hab ich noch ein Bugfix für unterschiedliche Domains eingebaut - was aber vermutlich mit dem hier nichts zu tun hat. 

Evt. müsste ich sonst den Code direkt mal sehen - wenn das okay wäre für dich.

**Comment by MacKP** [comment]
Hmm das dachte ich mir fast schon.. An sich ja super, dass es bei dir klappt ;-)
Ich mach mal ne kopie der Seite und melde mich dann, wenn ich was zum spielen für dich habe.

Eventuell finde ich bis da hin ja auch noch etwas heraus was das verursachen könnte...

Vielen Dank schon mal und viele Grüße

**Comment by Sioweb** [comment]
Das haben wir gefixt daher schließe ich das mal :)
