### ISSUE TITLE
Fehlermeldung direkt nach Installation

### ISSUE THREAD

**Issue by operatorone** [Sioweb/Glossar#16]
Nach der Installation in mein Contao 3.5.27 erhielt ich folgende globale Fehlermeldung. Wei könnte ich das beheben?

```
Fatal error: Uncaught exception Error with message Function name must be a string thrown in system/modules/Glossar/classes/Glossar.php on line 95
#0 system/modules/core/classes/FrontendTemplate.php(89): sioweb\contao\extensions\glossar\Glossar->searchGlossarTerms('...', 'fe_page')
#1 system/modules/core/pages/PageRegular.php(190): Contao\FrontendTemplate->output(true)
#2 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#3 index.php(20): Contao\FrontendIndex->run()
#4 {main}
```

**Comment by Sioweb** [comment]
Ho! Hast du php 7 am laufen?

**Comment by operatorone** [comment]
Hi, ja. Es läuft PHP-Version: 7.0.19.

**Comment by Sioweb** [comment]
Alles klar. PHP 7 rendert Variablen nun in einer anderen Reihenfolge. Ein Quickfix wäre in Zeile 95:

```
$this->$callback[0]->$callback[1]
// Zu
$this->{$callback[0]}->{$callback[1]}
```

Das sollte laufen. Ich bau den Glossar dann Zeitnah PHP7 Tauglich um :)

**Comment by operatorone** [comment]
Cool. Danke dir für den Quickfix. Die Fehlermeldung kam nicht mehr. Ich konfiguriere heute mal die Module und schaue, ob alees klappt :-)

**Comment by operatorone** [comment]
Hi, ich wollte nun mal ein paar Einträge im Glossar anlegen und sobald ich einen speichern möchte, bekomme ich folgende Fehlermeldung: 

`Fatal error: Cannot use 'String' as class name as it is reserved in /var/www/vhosts/relaunch.fraenkische.com/httpdocs/system/modules/core/library/Contao/String.php on line 28`

**Comment by operatorone** [comment]
Das hängt wahrscheinlich auch damit zusammen, dass das CMS auf PHP 7 läuft. Konnte ich den Recherchen im Netz entnehmen. Ich habe zwar einen Hotfix gefunden, weiß aber leider niht, wo ich ihn einbauen könnte. Es wäre super, wenn du dir das noch mal anschauen könntest, da ich das Glossar dringend für ein Projkt bräuchte.

`if (!version_compare(VERSION, '3.5', '<'))
  {
   $this->import('StringUtil');
  }
  else
  { 
   $this->import('String');
  }`

**Comment by Sioweb** [comment]
Ho!

tut mir leid dass ich mich nicht so schnell melde :)

Ja es liegt daran. In PHP 7 ist String ein reservierter Klassenname. Ich versuch ASAP eine PHP7 taugliche Version hochzuladen.

**Comment by operatorone** [comment]
Alles klar. Danke für deine Rückmeldung und deine Mühe.

**Comment by operatorone** [comment]
Hi, kannst du schon absehen, wann du die Erweiterung anpassen könntest?

**Comment by Sioweb** [comment]
Ho! 

Die Erweiterung sollte passen, zumindest auf meiner Stage tut sie das. Version Glossar 4.4.0 ist jetzt online.

**Comment by Sioweb** [comment]
Hat das Update bei dir funktioniert?

Lg

**Comment by operatorone** [comment]
Hi, danke für das Update. Hat gut geklappt. Falls ich noch etwas finde, melde ich mich ;-)
