### ISSUE TITLE
Zurück-Link mit Klasse versehen

### ISSUE THREAD

**Issue by operatorone** [Sioweb/Glossar#17]
Von Vorteil wäre es im Template ce_glossar.html5 den "zurück"-Link noch mit einer CSS-Klasse auszustatten. Dann kann man ihn besser für das Styling ansprechen

`<?php if($this->content) {?><a href="javascript:history.back();">Zurück</a><?php }?>
`

wird zu 

`<?php if($this->content) {?><a class="back" href="javascript:history.back();">Zurück</a><?php }?>
`

**Comment by Sioweb** [comment]
Bau ich ein :) ich werde aber vermutlich glossar_back verwenden, damit keine bestehenden Styles reinpfuschen, oder was meinst du?

**Comment by operatorone** [comment]
Ja, das ist ne gute Idee mit dem "glossar_back". Dann ist das klarer ansprechbar. Wenn jemand das generalisierter machen will, um z. B. alle Back-Buttons gleich zu machen, kann er im Template ja noch eine Klasse einfügen oder einfach im CSS mehrere Klassen für diese Formatierung definieren.

In Hinsicht Mehrsprachigkeit wäre es vielleicht auch gut gleich hier das Label abzufragen, um es ggf. hier zu manipulieren: $GLOBALS['TL_LANG']['MSC']['goBack'] = 'zurück';

Auch spannend wäre, wenn der zurücklink ein wirklicher Referer ist. Somit der Eintrag wirklich am entsprechenden Glossar hängt. Per Inserttag ginge das ja, nur halt nicht im Template da das ja nur PHP spricht.

**Comment by Sioweb** [comment]
Top :)
