### ISSUE TITLE
Pagination Klasse Link "Alle anzeigen"

### ISSUE THREAD

**Issue by operatorone** [Sioweb/Glossar#19]
Entschuldige, dass ich dich grade etwas bombardiere, aber mir ist noch etwas aufgefallen.

Im Template **glossar_pagination.html5** wäre es gut, wenn auch der Link für "Alle anzeigen" eine Klasse bekäme. Da ich die SPANs, sprich die * nicht in der Pagination haben will und das nur über Farben mache, sollte natürlich der erste Link auch wie ein "trueLink" behandelt werden können. Es kann auch auch sein, dass man ihn ausblenden möchte, deshalb hätte er eine eigene Klasse.

`<a href="<?php echo $this->showAllHref;?>" title=""><?php echo $this->showAllLabel;?></a>`

wird zu 

`<a class="allLabels" href="<?php echo $this->showAllHref;?>" title=""><?php echo $this->showAllLabel;?></a>`

**Comment by Sioweb** [comment]
Top :) Davon lebt der Glossar. Ich danke dir!

**Comment by operatorone** [comment]
Das freut mich. Wenn du schon am Code bist vielleicht könntest du dem letzt Link in der Pagination noch die Klasse .last geben, dann kann ich den margin-right auf 0 setzten.
