### ISSUE TITLE
Kennzeichnen von Wörtern in anderer Sprache

### ISSUE THREAD

**Issue by MacKP** [Sioweb/Glossar#2]
Im Grunde das selbe verhalten wie bei Abkürzungen, nur eben für andere Sprachen:
```
<span lang=”en”>Website</span>
```
Wäre ein schönes Feature :)

**Comment by Sioweb** [comment]
Gute Idee! Bau ich beim nächsten Update rein.

**Comment by Sioweb** [comment]
Ist eingebaut.
