### ISSUE TITLE
Pagination - Buchstaben ohne Inhalt

### ISSUE THREAD

**Issue by operatorone** [Sioweb/Glossar#24]
Es ist zu überlegen ob man vielleicht ein zweites Template oder eine Option schafft in der die Buchstaben die keinen Inhalt haben nicht als Link, sondern einfach als SPAN dargestellt werden. 

Ich denke da nur im Sinne des Benutzers, der zwar eine Meldung (empty message) erhält, sobald er auf einen Buchstaben ohne Inhalte klickt, aber ggf. wäre es besser die user experience immer positiv zu halten und nur die Buchstaben mit Inhalten als Link bereitzustellen.

**Comment by Sioweb** [comment]
Ho! Klingt gut. Schau mal im Inhaltselement sollte es möglich sein, nur Buchstaben zu verwenden die Inhalte haben, die anderen werden ausgeblendet. Aber ggf. die leeren als SPAN ausgeben ist gut, denn eine leere Pagination sieht nicht gut aus.
