### ISSUE TITLE
Verlinkte Begriffe ohne Vorschau

### ISSUE THREAD

**Issue by operatorone** [Sioweb/Glossar#25]
Gibt es eigentlich ein Möglichkeit einfach nur die Begriffe zu Verlinken ohne den Tooltip beim Hovern anzuzeigen?

**Comment by Sioweb** [comment]
Noch nicht, aber kann ich gerne einbauen. Klingt sehr nützlich.

**Comment by Sioweb** [comment]
Dafür gibt es beim nächsten Update dann eine Option in den Einstellungen.
