### ISSUE TITLE
Begriff ohne Content anzeigen

### ISSUE THREAD

**Issue by operatorone** [Sioweb/Glossar#26]
Bei einem Begriff ohne Content, der nur einen Teasertext hat, wäre es klasse, wenn nach dem Klick auf den Begriff einfach der im Glossar Buchstabe aufgerufen werden würde. 

Der Tooltip ist gut – ohne Frage - aber nicht immer (meist vom Kunden) gewollt.

**Comment by Sioweb** [comment]
Ich schau was ich hier tun kann, ob ich das so umsetzen kann.
