### ISSUE TITLE
Fehler bei Tooltip-Anzeige

### ISSUE THREAD

**Issue by operatorone** [Sioweb/Glossar#27]
Ich habe grade in Chrome versucht einen Tooltip anzuzeigen und erhilt folgende Meldung im Inspector:

`  | Uncaught SyntaxError: Unexpected token u in JSON at position 0 at m.parseJSONat (anonymous function)770772080fc3.js:2:80044glossar.js:102:48
-- | --`

Im Firefox öffnet sich der Tooltip auch nicht. Habe ich vergessen was einzustellen?

**Comment by operatorone** [comment]
Habe mich falsch ausgedrückt. Der Tooltip selbst erscheint, hat nur keinen sichtbaren Inhalt.

`<span lang="de" class="glossar glossar_no_content glossar_6" data-maxwidth="450" data-maxheight="300" data-glossar="23">
	Automotive</span>`

`<div class="glossar_layer" style="position: absolute; top: 1881px; left: 1095.67px; max-width: 450px; max-height: 300px;"></div>`

`<div id="qfqfqfqfqfqwfqwfqwfqf" style="z-index: 2147483647; position: fixed; bottom: 0px; left: 0px; right: 0px; background-color: rgb(244, 67, 54); color: rgb(255, 255, 255); padding: 5px; font-family: monospace; font-size: 12px; line-height: 1; text-overflow: ellipsis; word-wrap: break-word; white-space: nowrap; overflow: hidden;">Uncaught SyntaxError: Unexpected token u in JSON at position 0</div>`

**Comment by Sioweb** [comment]
Das sieht spannend aus, kannst du mir den genauen Inhalt senden den der Tooltip ausgeben soll? Evt. ist da ein Sonderzeichen im Quelltext welches den JSON verhühnert. Ich schau sonst auch gerne selbst im System nach, wenn du mir die Zugangsdaten senden willst.

**Comment by operatorone** [comment]
Der Inhalt ist eigentlich  nur "Bereich der sich mit der Herstellung von Fahrzeugen beschäftigt." als Teaser oder was genau meintest du mit Inhalt ;-)

**Comment by Sioweb** [comment]
Der Tooltip wird per Ajax geladen, ich müsste wissen was der zurückbekommt. Mit den Entwicklertools in Chrome kannst du das unter Netzwerk sehen. Da stellst du XHR ein und fährst mal über einen Begriff, dann wird ein AJAX abgefeuert. Den Eintrag müsstest du anklicken und mir das Result im rechten Fenster senden :)

Ich hoffe das klingt nicht zu kompliziert o:

**Comment by operatorone** [comment]
Ich hoffe, das hier ist der richtige Output :-)

Request URL:http://xxx
Request Method:GET
Status Code:204 No Content
Remote Address:178.63.16.202:80
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Cache-Control:no-store, no-cache, must-revalidate
Connection:keep-alive
Content-Length:0
Content-Type:text/html; charset=UTF-8
Date:Tue, 01 Aug 2017 13:09:23 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Pragma:no-cache
Server:nginx
X-Ajax-Location:http://xxx
X-Powered-By:PleskLin
X-Powered-By:PHP/7.0.21
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4,tr;q=0.2
Authorization:Basic MTIzOjQ1Ng==
Cache-Control:no-cache
Connection:keep-alive
Cookie:_et_coid=877151c81a4c6345eca59294c995d945; PHPSESSID=so0cc48qlttiec2g5qrjvcu173
Host:xxx
Pragma:no-cache
Referer:http://xxx
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
X-Requested-With:XMLHttpRequest

**Comment by Sioweb** [comment]
Ho! Danke für die Antwort :) ich hab sie wieder entfernt damit keine falschen Daten gesehen werden können. Du hast mir die Headers gesendet, in dem Feld kannst du über die Reiter darüber noch Response auswählen.

Das bräuchte ich.

**Comment by Sioweb** [comment]
![xhr](https://user-images.githubusercontent.com/1318048/28827525-22aa0be0-76ce-11e7-940b-a67740e41591.PNG)

**Comment by operatorone** [comment]
Hi, das habe ich probiert. Leider bekomme ich da nichts angezeigt. Die einzigen Ausgabe wäre einmal die Console:
`
(index):1 Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.m.parseJSON (770772080fc3.js:2)
    at glossar.js:102
m.parseJSON @ 770772080fc3.js:2
(anonymous) @ glossar.js:102
`
und von der index.php bekomme ich unter Response nur im Fenster "Failes to load response data" angezeigt.

**Comment by Sioweb** [comment]
Hallo Tilmann,

eben konnte ich ein paar deiner Tickets auf Github erledigen. Das Update
4.4.5 ist in wenigen Minuten live. Könntest du das Update bei dir
einspielen und schauen ob es für dich so passt? In den Systemeinstellungen
von Contao gibt es nun zwei neue Einstellungen die du aktivieren musst
"Tooltips deaktivieren" und "Begriffe immer verlinken". Damit gehen keine
Tooltipps mehr auf und Begriffe werden verlinkt, auch wenn nur ein Teaser
vorhanden ist.

Bei dem Teaser wäre ich vorsichtig, aus SEO-Sicht ist das duplicate
content, wenn der Teaser auf der Glossar-Liste steht und auf der
Detailseite.

Den JSON-Fehler kann ich leider nicht reproduzieren. Wenn du mir
Zugangsdaten sendest, schau ich es mir aber gerne an :)

Lg
Sascha

**Comment by operatorone** [comment]
Hi Sascha,

ich habe die Erweiterung aktualisiert und das schaut super aus :-) Der Fehler beim Tooltip ist zwar noch da, aber da komme ich noch mal auf dich zu. Bezüglich des Duplicate Contents bezogen auf die Begriffe die nur einen Teaser haben, kann man dem vielleicht mit einer Option entgegenwirken, der die Robots.txt der Teaserseite auf no-index stellt, sofern das eine sinnvolle Idee ist ;-)

Viele Grüße,
Tilman
