### ISSUE TITLE
Symbol hinter Glossar-Link im Text

### ISSUE THREAD

**Issue by operatorone** [Sioweb/Glossar#28]
Hi Sascha,

ich wollte gerne hinter jedem gefundenen Eintrag im Fließtext ein Icon anzeigen. Das kann ich zwar per CSS über :after und content machen, aber kann ich das auch in einem Template definieren? Sprich ein i-Tag hinter dem a-Tag platzieren, damit mir die text-decoration nicht unter das Icon geht.

Viele Grüße,
Tilman

**Comment by Sioweb** [comment]
Ho!

Im templates-Verzeichnis des Modules liegen die Templates :) https://github.com/Sioweb/Glossar/tree/master/templates/replacement

Ich denke die brauchst du.

**Comment by operatorone** [comment]
Super, danke dir. Hab es gefunden.
