### ISSUE TITLE
Glossar mit Contao 4.4 - Abkürzungen

### ISSUE THREAD

**Issue by MacKP** [Sioweb/Glossar#30]
Ich nutze gerade den Glossar mit Contao 4.4 (vielen Dank schon mal für die Umsetzung dafür!).
Leider funktionieren Abkürzungen noch nicht wie gewünscht:
Archiv ist angelegt und konfiguriert. Funktioniert an sich auch.
Neuen Eintrag anlegen
- Begriffsart auf 'ABBR - Abkürzung' stellen
- Suchwort/Stichwort eingeben
- Teaser ausfüllen
Der Begriff wird im Frontend gefunden und passend als Abkürzung ausgezeichnet. Es wird nur kein title ausgegeben. Kann es sein, dass das Umstellen auf Abkürzung noch nicht richtig funktioniert? Bei der alten Version war ja bei einer Abkürzung nicht mehr der Teaser zu sehen beim Ausfüllen im Backend, sondern die Beschreibung der Abkürzung.

Ich hoffe ich habe das verständlich beschrieben...

Viele Grüße

**Comment by Sioweb** [comment]
Ho! Danke 

schau ich mir asap an.

Lg
Sascha

**Comment by Sioweb** [comment]
In Contao 4 ist der Bug behoben. In Glossar 3 tritt der soweit ich das beurteilen kann nicht auf.
