### ISSUE TITLE
Fehlender Parameter beim Bearbeiten eines Glossareintrags

### ISSUE THREAD

**Issue by simonreitinger** [Sioweb/Glossar#35]
Mir ist gerade ein Bug aufgefallen:

Wenn man den Inhalt eines Eintrags bearbeiten will, kommt man auf eine leere Seite. Hier fehlt in der URL der Parameter `&table=tl_content`.

**Comment by Sioweb** [comment]
HI Simon & danke, 

ich nehme an für den Glossar ab Contao Version 4? Falls ja, sollte das Problem nun behoben sein.

Vielen Dank & LG
Sio
