### ISSUE TITLE
Fehlermeldung wenn FAQ deaktiviert im Backend

### ISSUE THREAD

**Issue by MacKP** [Sioweb/Glossar#7]
Wenn ich FAQ deaktiviert habe bekomme ich im Frontend diese Ausgabe:
`Fatal error: Class 'ModuleFaqList' not found in /www/htdocs/.../.../system/modules/Glossar/classes/GlossarFAQ.php on line 18`

Auch bei der Installation gibt es Probleme, wenn FAQ und z.B. Kommentare ausgeschaltet sind...

Viele Grüße

PS: Version von heute, per Hand installiert.

**Comment by Sioweb** [comment]
Fehler behoben. FAQ Event und News müssen nicht mehr aktiv sein.
