### ISSUE TITLE
Glossar zurücksetzen ergibt Fehlermeldung

### ISSUE THREAD

**Issue by MacKP** [Sioweb/Glossar#8]
Hallo,
wenn ich in der Systemwartung den Glossar anzeigen lasse und dann zurücksetzen möchte, dann kommt beim klick auf speichern diese Fehlermeldung:
`Fatal error: Call to private method sioweb\contao\extensions\glossar\RebuildGlossar::clearGlossar() from context 'sioweb\contao\extensions\glossar\Glossar' in /www/htdocs/.../.../.../system/modules/Glossar/classes/Glossar.php on line 32`

Viele Grüße

PS: Version von heute, per hand installiert

**Comment by Sioweb** [comment]
Ich hab die Funktion jetzt einfach mal auf public gestellt, da sie ohnehin leer ist. Läufts jetzt? ^^

**Comment by MacKP** [comment]
Hmm bereinigen kann ich den Glossar aktuell nicht und neu aufbauen leider auch nicht. Ich bekomme nur die Meldung, das ein Fehler aufgetreten ist (und ja, ich hab eingestellt, das mir Fehlermledungen angezeigt werden). Leider steht auch im log von Contao nichts.
Konnte also die anderen Features noch nich testen ^^

**Comment by MacKP** [comment]
OH, gelogen.. Das Contao Backend hat mir zwar gesagt, das ich Fehlermeldungen anzeigen lasse.. stimmte aber nicht.
Diese Fehlermeldung kommt beim Glossar aufbauen:
`Fatal error: Uncaught exception Exception with message Query error: Unknown column 'tl_news_archive.glossar_disallow' in 'where clause' (SELECT tl_news_archive.*, j1.id AS jumpTo__id, j1.pid AS jumpTo__pid, j1.sorting AS jumpTo__sorting, j1.tstamp AS jumpTo__tstamp, j1.title AS jumpTo__title, j1.alias AS jumpTo__alias, j1.type AS jumpTo__type, j1.pageTitle AS jumpTo__pageTitle, j1.language AS jumpTo__language, j1.robots AS jumpTo__robots, j1.description AS jumpTo__description, j1.redirect AS jumpTo__redirect, j1.jumpTo AS jumpTo__jumpTo, j1.url AS jumpTo__url, j1.target AS jumpTo__target, j1.dns AS jumpTo__dns, j1.staticFiles AS jumpTo__staticFiles, j1.staticPlugins AS jumpTo__staticPlugins, j1.fallback AS jumpTo__fallback, j1.adminEmail AS jumpTo__adminEmail, j1.dateFormat AS jumpTo__dateFormat, j1.timeFormat AS jumpTo__timeFormat, j1.datimFormat AS jumpTo__datimFormat, j1.createSitemap AS jumpTo__createSitemap, j1.sitemapName AS jumpTo__sitemapName, j1.useSSL AS jumpTo__useSSL, j1.autoforward AS jumpTo__autoforward, j1.protected AS jumpTo__protected, j1.groups AS jumpTo__groups, j1.includeLayout AS jumpTo__includeLayout, j1.layout AS jumpTo__layout, j1.mobileLayout AS jumpTo__mobileLayout, j1.includeCache AS jumpTo__includeCache, j1.cache AS jumpTo__cache, j1.includeChmod AS jumpTo__includeChmod, j1.cuser AS jumpTo__cuser, j1.cgroup AS jumpTo__cgroup, j1.chmod AS jumpTo__chmod, j1.noSearch AS jumpTo__noSearch, j1.cssClass AS jumpTo__cssClass, j1.sitemap AS jumpTo__sitemap, j1.hide AS jumpTo__hide, j1.guests AS jumpTo__guests, j1.tabindex AS jumpTo__tabindex, j1.accesskey AS jumpTo__accesskey, j1.published AS jumpTo__published, j1.start AS jumpTo__start, j1.stop AS jumpTo__stop, j1.disableGlossar AS jumpTo__disableGlossar, j1.glossar_no_fallback AS jumpTo__glossar_no_fallback, j1.glossar AS jumpTo__glossar, j1.fallback_glossar AS jumpTo__fallback_glossar, j1.glossar_time AS jumpTo__glossar_time, j1.cookiebar_enable AS jumpTo__cookiebar_enable, j1.cookiebar_message AS jumpTo__cookiebar_message, j1.cookiebar_jumpTo AS jumpTo__cookiebar_jumpTo, j1.cookiebar_position AS jumpTo__cookiebar_position, j1.cookiebar_placement AS jumpTo__cookiebar_placement, j1.cookiebar_button AS jumpTo__cookiebar_button FROM tl_news_archive LEFT JOIN tl_page j1 ON tl_news_archive.jumpTo=j1.id WHERE tl_news_archive.id IN('2','3') AND tl_news_archive.glossar_disallow = 1) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

#0 system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 system/modules/core/library/Contao/Model.php(1082): Contao\Database\Statement->execute(Array)
#2 system/modules/core/library/Contao/Model.php(958): Contao\Model::find(Array)
#3 system/modules/Glossar/models/GlossarNewsArchiveModel.php(23): Contao\Model::findBy(Array, Array, Array)
#4 system/modules/Glossar/classes/GlossarNews.php(60): GlossarNewsArchiveModel::findByPidsAndInactiveGlossar(Array)
#5 system/modules/Glossar/classes/RebuildGlossar.php(194): sioweb\contao\extensions\glossar\GlossarNews->generateUrl(Array)
#6 system/modules/core/modules/ModuleMaintenance.php(52): sioweb\contao\extensions\glossar\RebuildGlossar->run()
#7 system/modules/core/classes/BackendModule.php(98): Contao\ModuleMaintenance->compile()
#8 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#9 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#10 contao/main.php(20): Contao\BackendMain->run()
#11 {main}
`

Diese Fehlermeldung kommt bei Glossar zurücksetzen:
`
Fatal error: Uncaught exception Exception with message Query error: Unknown column 'glossar_time' in 'where clause' (UPDATE tl_news SET glossar = NULL,fallback_glossar = NULL,glossar_time = 1468595601 WHERE glossar_time != 1468595601) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

#0 system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 system/modules/Glossar/classes/GlossarNews.php(26): Contao\Database\Statement->execute(1468595601, 1468595601)
#2 system/modules/Glossar/classes/Glossar.php(32): sioweb\contao\extensions\glossar\GlossarNews->clearGlossar(1468595601)
#3 system/modules/core/classes/PurgeData.php(77): sioweb\contao\extensions\glossar\Glossar->purgeGlossar()
#4 system/modules/core/modules/ModuleMaintenance.php(52): Contao\PurgeData->run()
#5 system/modules/core/classes/BackendModule.php(98): Contao\ModuleMaintenance->compile()
#6 system/modules/core/classes/Backend.php(423): Contao\BackendModule->generate()
#7 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('maintenance')
#8 contao/main.php(20): Contao\BackendMain->run()
#9 {main}
`
Beide male sind also Tabellen/Spalten nicht vorhanden, die eigentlich da sein sollten (beim update musste/sollte ich auch Spalten löschen).

Viele Grüße

**Comment by Sioweb** [comment]
Danke, ich habe die Daten kurzzeitig fehlerhaft hochgeladen, ist noch ein Build in deiner Installation verfügbar? Oder ist das die aktuelle Version?

**Comment by MacKP** [comment]
Äh? Ich kann das noch mal runter und wieder hochladen und testen, wenn du das meinst? ^^

**Comment by Sioweb** [comment]
Naja an dem Tag hab ich kurz nach dem Hochladen noch ein paar Kleinigkeiten geändert, vielleicht war das kurz nachdem du getestet hast. Also wenn du es nochmal installieren könntest wäre das super :)

**Comment by MacKP** [comment]
Ne, bekomme leider immer noch diese Fehlermeldung :(
DB brauchte ich nicht aktualisieren nach dem erneuten upload der Erweiterung (die alte Version hatte ich vorsichtshalber auch erst entfernt).

Viele Grüße

**Comment by MacKP** [comment]
Super. Ich bekomme keine Fehlermeldung mehr (hab es jetzt mal in einer neuen Installation ausprobiert). Eventuell hatte ich das Problem noch, weil ich mir das hier runter geladen hatte und nicht über das ER. Ich hab jetzt extra eine Testinstall ohne Composer um mir immer die aktuelle Version runter zu laden ^^
