### ISSUE TITLE
z.B. als Abkürzung wird nicht gefunden

### ISSUE THREAD

**Issue by MacKP** [Sioweb/Glossar#9]
Version: Von Heute per Hand runtergeladen und installiert.

Ich habe als Abkürzung 'z.B.' und als Beschreibung 'zum Beispiel'. Leider wird der Begriff nicht gefunden und mit <abbr> versehen.

Viele Grüße

**Comment by MacKP** [comment]
Noch ein paar Tests. 'u.a.' wird auch nicht gefunden.
Kann es sein, das es an der Pluralsuche bzw. deren Einstellung liegt?
Ich kann da ja schlecht den Punkt raus nehmen, wenn der dann am Ende von einem Satz immer den Punkt mit nimmt danach oder? Ich glaub das ist ein echt schwieriges Problem. Eventuell müsste es möglich sein für solche Worte Ausnahmen zu setzen?

Viele Grüße

**Comment by Sioweb** [comment]
Ho! Das ist behoben in der Version 4.3.2

**Comment by MacKP** [comment]
Kann ich bestätigen. Funktioniert jetzt bei mir auch ohne Probleme an der Stelle. Vielen Dank!
